version: '3'

services:
  web:
    build: .
    expose:
      - "8000"  # Note that we are not binding to host's port 80 anymore
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./webroot:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email diagnosaipa@gmail.com --agree-tos --no-eff-email --staging -d 34.68.83.48
