version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "diagnosa_backend.wsgi:application", "--bind", "0.0.0.0:8000"]

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/api.mikostop.com/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/api.mikostop.com/privkey.pem:/etc/ssl/private/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
