# Generated by Django 4.2.5 on 2023-09-21 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pulmonary_TB', models.BooleanField(default=False)),
                ('has_solid_organ_malignancy', models.BooleanField(default=False)),
                ('is_galactomannan_positive', models.BooleanField(default=False)),
                ('is_receiving_systemic_corticosteroids', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IPAPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa_prob', models.FloatField()),
                ('total_score', models.IntegerField()),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.formdata')),
            ],
        ),
    ]
