# Generated by Django 4.2.5 on 2023-09-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='is_probable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipaprediction',
            name='is_probable',
            field=models.BooleanField(default=False),
        ),
    ]
