# Generated by Django 4.2.5 on 2023-09-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_formdata_is_probable_ipaprediction_is_probable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaprediction',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
